# name: Build and Deploy to Docker Hub

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build the project
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to Docker Hub
#         uses: docker/build-push-action@v3
  
#       -name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
 
#       -name: Build and push docker image for frontend
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./docker/Dockerfile.web
#           push: true
#           tags: sharmakeshav54126293/turing-frontend:latest
#           build-args: |
#             NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
#             NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
#             NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET }}
#             NEXT_PUBLIC_ACCESS_KEY_ID: ${{ secrets.NEXT_PUBLIC_ACCESS_KEY_ID }}
#             NEXT_PUBLIC_SECRET_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_SECRET_ACCESS_KEY }}
#             NEXT_PUBLIC_REGION: ${{ secrets.NEXT_PUBLIC_REGION }}
#             NEXT_PUBLIC_BUCKET_NAME: ${{ secrets.NEXT_PUBLIC_BUCKET_NAME }}
#             JWT_SECRET: ${{ secrets.JWT_SECRET }}
#             NEXT_PUBLIC_FRONTEND_URL: ${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}
#             DATABASE_URL: ${{ secrets.DATABASE_URL }}
#             GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
#             GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#             GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

#       -name: Build and push docker to backend
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           file: ./docker/Dockerfile.backend
#           push: true
#           tags: sharmakeshav54126293/turing-backend:latest
#           build-args: |
#             NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
#             NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
#             NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: ${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET }}
#             NEXT_PUBLIC_ACCESS_KEY_ID: ${{ secrets.NEXT_PUBLIC_ACCESS_KEY_ID }}
#             NEXT_PUBLIC_SECRET_ACCESS_KEY: ${{ secrets.NEXT_PUBLIC_SECRET_ACCESS_KEY }}
#             NEXT_PUBLIC_REGION: ${{ secrets.NEXT_PUBLIC_REGION }}
#             NEXT_PUBLIC_BUCKET_NAME: ${{ secrets.NEXT_PUBLIC_BUCKET_NAME }}
#             JWT_SECRET: ${{ secrets.JWT_SECRET }}
#             NEXT_PUBLIC_FRONTEND_URL: ${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}
#             DATABASE_URL: ${{ secrets.DATABASE_URL }}
#             GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
#             GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
#             GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

