version: '3.8'

services:
  frontend:
    image: sharmakeshav54126293/turing-frontend:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - 3008:3008
    build:
      context: .
      dockerfile: docker/Dockerfile.web
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: ${NEXT_PUBLIC_GOOGLE_CLIENT_SECRET}
        NEXT_PUBLIC_AWS_ACCESS_KEY_ID: ${NEXT_PUBLIC_AWS_ACCESS_KEY_ID}
        NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY: ${NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY}
        NEXT_PUBLIC_AWS_REGION: ${NEXT_PUBLIC_AWS_REGION}
        NEXT_PUBLIC_AWS_BUCKET_NAME: ${NEXT_PUBLIC_AWS_BUCKET_NAME}
        JWT_SECRET: ${JWT_SECRET}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
        DATABASE_URL: ${DATABASE_URL}
        GEMINI_API_KEY: ${GEMINI_API_KEY}

  backend:
    image: sharmakeshav54126293/turing-backend:latest
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
        NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: ${NEXT_PUBLIC_GOOGLE_CLIENT_SECRET}
        NEXT_PUBLIC_AWS_ACCESS_KEY_ID: ${NEXT_PUBLIC_AWS_ACCESS_KEY_ID}
        NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY: ${NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY}
        NEXT_PUBLIC_AWS_REGION: ${NEXT_PUBLIC_AWS_REGION}
        NEXT_PUBLIC_AWS_BUCKET_NAME: ${NEXT_PUBLIC_AWS_BUCKET_NAME}
        JWT_SECRET: ${JWT_SECRET}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
        DATABASE_URL: ${DATABASE_URL}
        GEMINI_API_KEY: ${GEMINI_API_KEY}

